
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/sim::BeamGateInfo",
  "LCGReflex/std::vector<sim::BeamGateInfo>",
  "LCGReflex/std::vector<int>",
  "LCGReflex/sim::LBNE10ktPhotons",
  "LCGReflex/std::vector<sim::LBNE10ktPhotons>",
  "LCGReflex/sim::OnePhoton",
  "LCGReflex/std::vector<sim::OnePhoton>",
  "LCGReflex/sim::SimPhotons",
  "LCGReflex/std::vector<sim::SimPhotons>",
  "LCGReflex/sim::SimChannel",
  "LCGReflex/std::vector<sim::SimChannel>",
  "LCGReflex/sim::IDE",
  "LCGReflex/std::vector<sim::IDE>",
  "LCGReflex/std::pair<unsigned short,std::vector<sim::IDE> >",
  "LCGReflex/std::map<unsigned short,std::vector<sim::IDE> >",
  "LCGReflex/art::Wrapper<std::vector<sim::BeamGateInfo> >",
  "LCGReflex/art::Wrapper<std::vector<int> >",
  "LCGReflex/art::Wrapper<std::vector<sim::LBNE10ktPhotons> >",
  "LCGReflex/art::Wrapper<std::vector<sim::SimPhotons> >",
  "LCGReflex/art::Wrapper<std::vector<sim::SimChannel> >",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

